# Generated by Django 4.1 on 2022-09-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_block_department_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='block',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.CharField(max_length=30),
        ),
    ]
